"""Mean evidence age at moving decisions versus the sweep value L + P/2 (no fitted parameter).

If verdicts start every P seconds and each becomes available L seconds after its capture proxy, and a
policy moves regardless of age, the age consumed at moving decisions sweeps from L to P + L, so its
mean is about L + P/2 (assuming decisions are spread evenly over the sweep). The age-aware rule departs
from this value when it refuses motion on old evidence. P and L come from each run's evidence bundles
(duty_cycle_results.json); observed mean moving age comes from the frozen run-level audit.
"""
import json, statistics as st
from pathlib import Path
HERE = Path(__file__).resolve().parent
def _find(rel):
    for base in (HERE.parent.parent, HERE.parents[1] / "10_hardware_manuscript_2026-09-24"):
        if (base / rel).exists():
            return base / rel
    raise FileNotFoundError(rel)
duty = {r["run"]: r for r in json.loads((HERE / "duty_cycle_results.json").read_text())["runs"]}
audit = [r for r in json.loads(_find("analysis/exploratory_patterns_2026-10-02/pattern_results.json").read_text())["runs"]
         if r["campaign"] == "timed_margin_compare"]
cells = {}
for r in audit:
    d = duty[r["run"]]
    cells.setdefault((r["method"], r["rate"]), []).append((1000 * (d["L_s"] + d["P_s"] / 2), r["mean_moving_age_ms"]))
out = {"note": __doc__, "cells": {}}
for (m, rate), v in sorted(cells.items(), key=lambda kv: (kv[0][1], kv[0][0])):
    pred = st.mean(a for a, _ in v); obs = st.mean(b for _, b in v)
    out["cells"][f"{m}-{rate}"] = {"L_plus_half_P_ms": pred, "observed_mean_moving_age_ms": obs, "difference_ms": obs - pred,
                                  "run_level_max_abs_difference_ms": max(abs(b - a) for a, b in v)}
fixed = [c for k, c in out["cells"].items() if not k.startswith("AEGIS") or k.endswith("normal")]
out["fixed_buffer_and_normal_AEGIS_max_abs_cell_difference_ms"] = max(abs(c["difference_ms"]) for c in fixed)
(HERE / "age_reuse_model_results.json").write_text(json.dumps(out, indent=2) + "\n")
rows = []
for k, c in out["cells"].items():
    m, rate = k.split("-")
    rows.append(f"{rate.capitalize()} & {m} & {c['L_plus_half_P_ms']:.1f} & {c['observed_mean_moving_age_ms']:.1f} & {c['difference_ms']:+.1f}\\\\".replace("+-", "$-$").replace(" -", " $-$"))
tex = [r"% Generated by age_reuse_model.py; equal-run means, n=4 per cell.",
       r"\begin{table}[H]\centering\small",
       r"\caption{Mean evidence age at moving decisions compared with the sweep value $L+P/2$, in ms, where $P$ is each run's update period and $L$ its capture-proxy-to-inference-end latency. A policy that moves regardless of age is expected to lie near $L+P/2$; the age-aware rule departs from it when it refuses motion on old evidence. No parameter is fitted.}\label{tab:age-sweep}",
       r"\begin{tabular}{@{}llrrr@{}}", r"\toprule Cadence & Method & $L+P/2$ & Observed & Difference\\ \midrule", *rows,
       r"\bottomrule", r"\end{tabular}", r"\end{table}"]
(HERE / "age_reuse_model_table.tex").write_text("\n".join(tex) + "\n")
for k, c in out["cells"].items():
    print(f"{k:16} L+P/2={c['L_plus_half_P_ms']:6.1f} obs={c['observed_mean_moving_age_ms']:6.1f} diff={c['difference_ms']:+6.1f} run-max={c['run_level_max_abs_difference_ms']:.1f}")
print("max |diff| fixed-buffer + normal AEGIS:", round(out["fixed_buffer_and_normal_AEGIS_max_abs_cell_difference_ms"], 1))
