"""Build supplementary LaTeX tables from exact_permutation_results.json and duty_cycle_results.json."""
import json
from pathlib import Path
HERE = Path(__file__).resolve().parent; OUT = (HERE.parent / "source/analysis") if (HERE.parent / "source").exists() else HERE
ex = json.loads((HERE / "exact_permutation_results.json").read_text())
du = json.loads((HERE / "duty_cycle_results.json").read_text())
NAME = {"age": "Mean moving age (ms)", "sep": "Separation (mm)", "time": "Carry-to-delivery (s)", "old": "Age $>0.6$ s (\\%)"}
ps = lambda p: "0.029" if abs(p - 2 / 70) < 1e-9 else f"{p:.2f}"
num = lambda x: f"{x:+.1f}".replace("-", "$-$")
ivl = lambda r: "[" + f"{r[0]:.1f}, {r[1]:.1f}".replace("-", "$-$") + "]"
rng = lambda r: f"{r[0]:.1f}--{r[1]:.1f}"
L = [r"% Generated by build_supp_tables.py; exact two-sided permutation, 70 reassignments, unadjusted.",
     r"{\footnotesize\setlength{\tabcolsep}{3.5pt}", r"\begin{longtable}{@{}lllrrrrc@{}}",
     r"\caption{Exact permutation tests on run-level values of the primary campaign. Difference is AEGIS minus reference; ranges list the four run values per group. Complete separation means the two run sets do not overlap, which yields the minimum attainable $p=2/70$. The compatibility interval contains the location shifts that do not completely separate the shifted runs (coverage $1-2/70\approx0.971$).}\label{tab:exact-full}\\",
     r"\toprule Cadence&Reference&Metric&Difference&Interval&AEGIS runs&Reference runs&$p$\\ \midrule\endfirsthead",
     r"\toprule Cadence&Reference&Metric&Difference&Interval&AEGIS runs&Reference runs&$p$\\ \midrule\endhead"]
for e in ex["between_method"]:
    L.append(f'{e["rate"].capitalize()}&{e["reference"]}&{NAME[e["metric"]]}&{num(e["AEGIS_minus_ref"])}&{ivl(e["compatibility_interval"])}&{rng(e["AEGIS_range"])}&{rng(e["ref_range"])}&{ps(e["p"])}\\\\')
L.append(r"\midrule")
L.append(r"\multicolumn{8}{@{}l}{\emph{Normal-to-slow change, AEGIS minus reference (four matched changes per method)}}\\")
for e in ex["cadence_change"]:
    L.append(f'Change&{e["reference"]}&{NAME[e["metric"]]}&{num(e["AEGIS_change_minus_ref_change"])}&{ivl(e["compatibility_interval"])}&&&{ps(e["p"])}\\\\')
L += [r"\bottomrule", r"\end{longtable}}"]
(OUT / "supp_exact_full_table.tex").write_text("\n".join(L) + "\n")

D = [r"% Generated by build_supp_tables.py from duty_cycle_results.json.",
     r"\begin{table}[H]\centering\small",
     r"\caption{First-order duty-cycle account of AEGIS score holds, per primary run. $P$: median start-to-start interval of evidence bundles consumed during carry; $L$: mean proxy-to-inference-end latency of those bundles; $\phi=\min\{1,\max[0,(P+L-T_\infty)/P]\}$ with $T_\infty=586.5$ ms; $\delta_m$, $\delta_h$: mean intervals between moving and between score-hold decisions; $\phi_s$: $\phi$ with the decision-sampling terms $-\delta_m/2+\delta_h/2$ added to the numerator; observed: score-held share of hazard-present, valid \textsc{object} interval time.}\label{tab:duty}",
     r"\begin{tabular}{@{}lrrrrrrrr@{}}", r"\toprule Run&$P$&$L$&$P+L$&$\delta_m$&$\delta_h$&$\phi$&$\phi_s$&Observed\\ &(ms)&(ms)&(ms)&(ms)&(ms)&&&\\ \midrule"]
for r in [x for x in du["runs"] if x["method"] == "AEGIS"]:
    D.append(f'\\texttt{{{r["run"].replace("_", chr(92)+"_")}}}&{1000*r["P_s"]:.0f}&{1000*r["L_s"]:.0f}&{1000*(r["P_s"]+r["L_s"]):.0f}&{1000*r["d_move_s"]:.0f}&{"---" if r["d_hold_s"] is None else f"{1000*r['d_hold_s']:.0f}"}&{r["predicted_hold_fraction"]:.2f}&{r["predicted_hold_fraction_sampled"]:.2f}&{r["observed_hold_fraction"]:.2f}\\\\')
D.append(r"\midrule")
for k in ("AEGIS-normal", "AEGIS-slow"):
    c = du["cells"][k]
    D.append(f'{k.replace("AEGIS-","AEGIS, ")} mean&{c["P_ms"]:.0f}&{c["L_ms"]:.0f}&{c["P_plus_L_ms"]:.0f}&{c["d_move_ms"]:.0f}&{"---" if c["d_hold_ms"] is None else f"{c['d_hold_ms']:.0f}"}&{c["predicted_hold_fraction"]:.2f}&{c["predicted_hold_fraction_sampled"]:.2f}&{c["observed_hold_fraction_equal_run"]:.2f}\\\\')
D += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
(OUT / "duty_cycle_table.tex").write_text("\n".join(D) + "\n")
print(open(OUT / "duty_cycle_table.tex").read())
