"""Exact two-sided permutation tests on run-level values of the 24-run primary campaign.

Reads the frozen per-run audit (pattern_results.json); writes JSON and a LaTeX table.
No observation is changed. With four runs per group there are C(8,4)=70 reassignments,
so the smallest attainable two-sided p is 2/70 = 0.0286. p-values are unadjusted and descriptive.
"""
import itertools, json, statistics, hashlib
from pathlib import Path

HERE = Path(__file__).resolve().parent

def _find(*rels):
    """Locate an input in the release layout (paper-data/) or the local package layout."""
    for base in (HERE.parent.parent, HERE.parents[1] / "10_hardware_manuscript_2026-09-24"):
        for rel in rels:
            if (base / rel).exists():
                return base / rel
    raise FileNotFoundError(rels)
SRC = _find("analysis/exploratory_patterns_2026-10-02/pattern_results.json")
METRICS = {"age": "mean_moving_age_ms", "sep": "minimum_command_estimated_separation_mm",
           "time": "carry_to_delivery_s", "old": "moving_old_evidence_percent"}
LABEL = {"age": "Mean moving age (ms)", "sep": "Separation (mm)", "time": "Carry-to-delivery (s)",
         "old": "Age $>0.6$ s (\\%)"}

def exact_p(a, b):
    pool = a + b; n = len(a); obs = statistics.mean(a) - statistics.mean(b)
    hits = tot = 0
    for idx in itertools.combinations(range(len(pool)), n):
        g1 = [pool[i] for i in idx]; g2 = [pool[i] for i in range(len(pool)) if i not in idx]
        d = statistics.mean(g1) - statistics.mean(g2); tot += 1
        hits += abs(d) >= abs(obs) - 1e-9
    return obs, hits / tot, tot

def separated(a, b):
    return max(a) < min(b) or min(a) > max(b)

runs = [r for r in json.loads(SRC.read_text())["runs"] if r["campaign"] == "timed_margin_compare"]
assert len(runs) == 24
val = lambda m, r, k: [x[METRICS[k]] for x in sorted(runs, key=lambda x: (x["direction"], x["repetition"]))
                       if x["method"] == m and x["rate"] == r]
out = {"source": str(SRC.name), "source_sha256": hashlib.sha256(SRC.read_bytes()).hexdigest(),
       "test": "exact two-sided permutation of run-level means, 4 vs 4, 70 reassignments, unadjusted",
       "minimum_attainable_p": 2 / 70,
       "compatibility_interval": "inversion of the same test for a location shift: shifts that do not completely separate the shifted runs, [min A - max B, max A - min B]; coverage 1 - 2/70 = 0.971 under exchangeability", "between_method": [], "cadence_change": []}
for rate in ("normal", "slow"):
    for ref in ("Trust12", "Trust32"):
        for k in METRICS:
            a, b = val("AEGIS", rate, k), val(ref, rate, k)
            d, p, n = exact_p(a, b)
            out["between_method"].append({"rate": rate, "reference": ref, "metric": k, "AEGIS_minus_ref": d,
                                          "p": p, "complete_separation": separated(a, b),
                                          "compatibility_interval": [min(a) - max(b), max(a) - min(b)],
                                          "AEGIS_range": [min(a), max(a)], "ref_range": [min(b), max(b)]})
# slow-minus-normal nominal changes (matched by direction and repetition), compared between methods
for ref in ("Trust12", "Trust32"):
    for k in METRICS:
        ca = [s - n for s, n in zip(val("AEGIS", "slow", k), val("AEGIS", "normal", k))]
        cb = [s - n for s, n in zip(val(ref, "slow", k), val(ref, "normal", k))]
        d, p, n = exact_p(ca, cb)
        out["cadence_change"].append({"reference": ref, "metric": k, "AEGIS_change_minus_ref_change": d, "p": p,
                                      "compatibility_interval": [min(ca) - max(cb), max(ca) - min(cb)],
                                      "complete_separation": separated(ca, cb)})
for k in ("age", "time", "sep"):
    a, b = val("AEGIS", "slow", k), val("AEGIS", "normal", k)
    d, p, n = exact_p(a, b)
    out.setdefault("within_AEGIS_slow_minus_normal", []).append({"metric": k, "diff": d, "p": p})
(HERE / "exact_permutation_results.json").write_text(json.dumps(out, indent=2) + "\n")

iv = lambda x: "[" + f"{x[0]:.1f}, {x[1]:.1f}".replace("-", "$-$") + "]"
dif = lambda x: f"{x:+.1f}".replace("-", "$-$")
rows = []
for k in ("age", "sep", "time", "old"):
    es = [next(x for x in out["between_method"] if (x["rate"], x["reference"], x["metric"]) == (rate, ref, k))
          for rate in ("normal", "slow") for ref in ("Trust12", "Trust32")]
    rows.append(LABEL[k] + " & " + " & ".join(dif(e["AEGIS_minus_ref"]) + ("$^{*}$" if e["complete_separation"] else "") for e in es) + r"\\")
    rows.append(r"\quad interval & " + " & ".join("{\\footnotesize " + iv(e["compatibility_interval"]) + "}" for e in es) + r"\\")
tex = ["% Generated by exact_permutation.py from frozen run-level values; descriptive, unadjusted.",
       r"\begin{tabularx}{\linewidth}{X>{\raggedleft\arraybackslash}p{0.15\linewidth}>{\raggedleft\arraybackslash}p{0.15\linewidth}>{\raggedleft\arraybackslash}p{0.15\linewidth}>{\raggedleft\arraybackslash}p{0.15\linewidth}}",
       r"\toprule", r"&\multicolumn{2}{c}{Normal cadence}&\multicolumn{2}{c}{Slow cadence}\\",
       r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}",
       r"AEGIS minus&Trust12&Trust32&Trust12&Trust32\\", r"\midrule", *rows, r"\bottomrule", r"\end{tabularx}"]
(HERE / "exact_permutation_table.tex").write_text("\n".join(tex) + "\n")
for e in out["between_method"]:
    print(f'{e["rate"]:6} {e["reference"]:7} {e["metric"]:4} d={e["AEGIS_minus_ref"]:+8.2f} p={e["p"]:.3f} sep={e["complete_separation"]} A={e["AEGIS_range"][0]:.1f}-{e["AEGIS_range"][1]:.1f} R={e["ref_range"][0]:.1f}-{e["ref_range"][1]:.1f}')
for e in out["cadence_change"]:
    print("chg", e["reference"], e["metric"], f'{e["AEGIS_change_minus_ref_change"]:+.2f}', f'p={e["p"]:.3f}', e["complete_separation"])
print(out["within_AEGIS_slow_minus_normal"])
